### ISSUE TITLE
Blank page 

### ISSUE THREAD

**Issue by kzaaaa** [Felix45/movies-lite#12]
hello, everything works only the page is blank, is this normal or did I forget to do something?
![Capture1](https://user-images.githubusercontent.com/50947369/220795564-96977c92-83ff-4e33-a5ff-84ff8aa2d6e5.PNG)

**Comment by Felix45** [comment]
Hi @kzaaaa,

Thanks for taking your time and creating this issue, I'll check on what could be causing the error.
